# Generated by Django 4.0 on 2021-12-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
